export const LEDGER_ACTIONS = {
    SUBMIT_BILL: "SUBMIT_BILL",
    TRANSLATE: "TRANSLATE",
    EVIDENCE_BUNDLE: "EVIDENCE_BUNDLE",
    GATE_EVAL: "GATE_EVAL",
    AUDIT_EVAL: "AUDIT_EVAL",
    BUNDLE_COMPOSED: "BUNDLE_COMPOSED",
    PUBLISH_BUNDLE: "PUBLISH_BUNDLE",
    EMERGENCY_STOP: "EMERGENCY_STOP",
    EMERGENCY_RESUME: "EMERGENCY_RESUME",
    ROOM_HOP: "ROOM_HOP",
} as const;

export type LedgerAction = (typeof LEDGER_ACTIONS)[keyof typeof LEDGER_ACTIONS];
